import { Task, TaskStatus } from './types/task-status';
import { ModalTaskData } from '../components/TaskManager/types';
import dayjs from 'dayjs';

export interface KanbanColumn {
  id: string;
  title: string;
  status: TaskStatus;
  position: number;
}

export const defaultBoards: KanbanColumn[] = [
  {
    id: 'col-1',
    title: TaskStatus.NOT_STARTED,
    status: TaskStatus.NOT_STARTED,
    position: 1,
  },
  {
    id: 'col-2',
    title: TaskStatus.PENDING,
    status: TaskStatus.PENDING,
    position: 2,
  },
  {
    id: 'col-3',
    title: TaskStatus.IN_PROGRESS,
    status: TaskStatus.IN_PROGRESS,
    position: 3,
  },
  {
    id: 'col-4',
    title: TaskStatus.WAITING_TASK,
    status: TaskStatus.WAITING_TASK,
    position: 4,
  },
  {
    id: 'col-5',
    title: TaskStatus.DELAYED,
    status: TaskStatus.DELAYED,
    position: 5,
  },
  {
    id: 'col-6',
    title: TaskStatus.CANCELED,
    status: TaskStatus.CANCELED,
    position: 6,
  },
  {
    id: 'col-7',
    title: TaskStatus.COMPLETED,
    status: TaskStatus.COMPLETED,
    position: 7,
  },
];

export const boards: TaskStatus[] = [
  TaskStatus.NOT_STARTED,
  TaskStatus.PENDING,
  TaskStatus.IN_PROGRESS,
  TaskStatus.WAITING_TASK,
  TaskStatus.DELAYED,
  TaskStatus.CANCELED,
  TaskStatus.COMPLETED,
];

export const mockTasks: Task[] = [
  {
    id: 'task1',
    title: 'Task 1',
    status: TaskStatus.NOT_STARTED,
    assignee: 'Ruan Portella',
    priority: 'ALTA',
    position: 1,
    endDate: '2026-10-01',
    color: 'blue',
    labels: ['label1', 'label2'],
    tags: ['tag1', 'tag2'],
    createdAt: '2023-09-30',
    selected: false,
    attachments: [
      {
        id: 1,
        name: 'attachment1.png',
        size: '2MB',
        type: 'image/png',
      },
      {
        id: 2,
        name: 'attachment2.pdf',
        size: '1MB',
        type: 'application/pdf',
      },
    ],
    description: 'This is a description for Task 1.',
    creator: 'creator1',
    startDate: '2023-09-29',
  },
  {
    id: 'task2',
    title: 'Task 2',
    status: TaskStatus.PENDING,
    assignee: 'Daniel Santos',
    priority: 'MÉDIA',
    position: 2,
    endDate: '2025-07-25',
    color: 'green',
    labels: ['label3'],
    tags: ['tag3'],
    createdAt: '2025-07-25',
    selected: false,
    attachments: [],
    description: 'This is a description for Task 2.',
    creator: 'creator2',
    startDate: '2023-09-27',
  },
  {
    id: 'task3',
    title: 'Task 3',
    status: TaskStatus.IN_PROGRESS,
    assignee: 'Paulo Machado',
    priority: 'BAIXA',
    position: 3,
    endDate: '2025-07-02',
    color: 'red',
    labels: ['label4'],
    tags: ['tag4'],
    createdAt: '2023-09-26',
    selected: false,
    attachments: [],
    description: 'This is a description for Task 3.',
    creator: 'creator3',
    startDate: '2023-09-25',
  },
  {
    id: 'task4',
    title: 'Task 4',
    status: TaskStatus.WAITING_TASK,
    assignee: 'Fernanda Bucci',
    priority: 'PENDENTE',
    position: 4,
    endDate: '2023-10-04',
    color: 'yellow',
    labels: ['label5'],
    tags: ['tag5'],
    createdAt: '2023-09-24',
    selected: false,
    attachments: [],
    description: 'This is a description for Task 4.',
    creator: 'creator4',
    startDate: '2023-09-23',
  },
  {
    id: 'task5',
    title: 'Task 5',
    status: TaskStatus.DELAYED,
    assignee: 'Rainer',
    priority: 'ALTA',
    position: 5,
    endDate: '2023-10-05',
    color: 'purple',
    labels: ['label6'],
    tags: ['tag6'],
    createdAt: '2023-09-22',
    selected: false,
    attachments: [],
    description: 'This is a description for Task 5.',
    creator: 'creator5',
    startDate: '2023-09-21',
  },
  {
    id: 'task6',
    title: 'Task 6',
    status: TaskStatus.CANCELED,
    assignee: 'user6',
    priority: 'MÉDIA',
    position: 6,
    endDate: '2023-10-06',
    color: 'orange',
    labels: ['label7'],
    tags: ['tag7'],
    createdAt: '2023-09-20',
    selected: false,
    attachments: [],
    description: 'This is a description for Task 6.',
    creator: 'creator6',
    startDate: '2023-09-19',
  },
  {
    id: 'task7',
    title: 'Task 7',
    status: TaskStatus.COMPLETED,
    assignee: 'user7',
    priority: 'BAIXA',
    position: 7,
    endDate: '2023-10-07',
    color: 'pink',
    labels: ['label8'],
    tags: ['tag8'],
    createdAt: '2023-09-18',
    selected: false,
    attachments: [],
    description: 'This is a description for Task 7.',
    creator: 'creator7',
    startDate: '2023-09-17',
  },
  {
    id: 'task8',
    title: 'Task 8',
    status: TaskStatus.NOT_STARTED,
    assignee: 'user8',
    priority: 'PENDENTE',
    position: 8,
    endDate: '2023-10-08',
    color: 'brown',
    labels: ['label9'],
    tags: ['tag9'],
    createdAt: '2023-09-16',
    selected: false,
    attachments: [],
    description: 'This is a description for Task 8.',
    creator: 'creator8',
    startDate: '2023-09-15',
  },
  {
    id: 'task9',
    title: 'Task 9',
    status: TaskStatus.PENDING,
    assignee: 'user9',
    priority: 'ALTA',
    position: 9,
    endDate: '2023-10-09',
    color: 'gray',
    labels: ['label10'],
    tags: ['tag10'],
    createdAt: '2023-09-14',
    selected: false,
    attachments: [],
    description: 'This is a description for Task 9.',
    creator: 'creator9',
    startDate: '2023-09-13',
  },
];

export const defaultTask: ModalTaskData = {
  id: '',
  title: '',
  creator: '',
  assignee: '',
  status: 'NÃO INICIADA',
  startDate: dayjs(),
  endDate: dayjs(),
  description: '',
  tags: [],
  notify: false,
  file: null,
  priority: 'PENDENTE',
  type: 'Infraestrutura',
};

export const mapTaskToModalTaskData = (task: Task | null): ModalTaskData => {
  if (!task) return defaultTask;
  return {
    id: task.id,
    title: task.title,
    creator: task.creator || '',
    assignee: task.assignee || '',
    status: task.status,
    startDate: dayjs(task.startDate),
    endDate: dayjs(task.endDate),
    description: task.description || '',
    tags: task.tags || [],
    notify: false,
    file: null,
    priority: task.priority,
    type: 'Infraestrutura',
    attachments: task.attachments || [],
  };
};
